from schemas.schema import State, NewsArticle
from prompts import news_search_prompt
from agents.shared import get_user_profile, get_model, parse_news_search_params
from langchain_core.runnables import RunnableConfig
from langgraph.store.base import BaseStore
from langchain_core.messages import SystemMessage, ToolMessage, AIMessage
import configuration
from langchain.agents import create_agent
from datetime import datetime
from tools.newsapi import get_articles
import json

def news_searcher(state : State, config : RunnableConfig, store : BaseStore):
    # This agent is responsible for searching videos based on the user's preferences and the search parameters generated by the orchestrator.
    # # Get user profile

    model = get_model()
    
    configurable = configuration.Configuration.from_runnable_config(config)
    user_id = configurable.user_id
    user_profile = get_user_profile(user_id, store)
    
    raw_search_params = state["news_search_params"]
    search_params = parse_news_search_params(raw_search_params)
    assert search_params is not None, "news_search_params should not be None in news_search agent"   

    system_msg = news_search_prompt.PROMPT.format(
        news_search_params=search_params,
        user_profile=user_profile,
        today=datetime.now().strftime("%Y-%m-%d")
    )

    agent = create_agent(model, tools=[get_articles])

    # Use the LLM to generate a query
    result = agent.invoke({
        "messages": [SystemMessage(content=system_msg)]
    })

    # Extract articles from tool results
    articles: list[NewsArticle] = []
    for msg in reversed(result["messages"]):
        if isinstance(msg, ToolMessage):
            try:
                parsed = json.loads(msg.content) # type: ignore
                articles = [NewsArticle(**a) for a in parsed]
            except (json.JSONDecodeError, TypeError, KeyError):
                pass
            break
    print(f"\nNews Search Agent: Parsed {len(articles)} articles\n")

    # Get the agent's final text response
    final_response = ""
    for msg in reversed(result["messages"]):
        if isinstance(msg, AIMessage) and msg.content and not msg.tool_calls:
            final_response = str(msg.content)
            break

    # Return ToolMessage to orchestrator + articles to state
    last_state_message = state["messages"][-1]
    assert isinstance(last_state_message, AIMessage), \
        f"Expected AIMessage in state but got {type(last_state_message)}"
    tool_call_id = last_state_message.tool_calls[0]["id"]

    # news_summary = "\n".join([
    #     f"{i+1}. {art.title}\n"
    #     f"   Author: {art.author}\n"
    #     f"   Source: {art.source}\n"
    #     f"   Description: {art.description}\n"
    #     f"   Published at: {art.published_at}\n"
    #     f"   URL: {art.url}"
    #     for i, art in enumerate(articles)
    # ]) 

    # If I return the summary, the LLM will write a lot of stuff, taking some time.
    # return {
    #     "news": articles,
    #     "messages": [{
    #         "role": "tool",
    #         "content": f"Found {len(articles)} news articles\n{news_summary}.",
    #         "tool_call_id": tool_call_id
    #     }]
    # }

    # Return a simple message, this saves time
    return {
        "news": articles,
        "messages": [{
            "role": "tool",
            "content": f"Found {len(articles)} news articles. They are displayed to the user in the news tab section!",
            "tool_call_id": tool_call_id
        }]
    }