from schemas.schema import State, SearchParams
from prompts import news_search_prompt
import unicodedata
from agents.shared import get_user_profile, get_model, parse_search_params
from langchain_core.runnables import RunnableConfig
from langgraph.store.base import BaseStore
from langchain_core.messages import SystemMessage
from tools import rapidapi_youtube
import configuration

def searcher(state : State, config : RunnableConfig, store : BaseStore):
    # This agent is responsible for searching videos based on the user's preferences and the search parameters generated by the orchestrator.
    # # Get user profile

    model = get_model()
    
    configurable = configuration.Configuration.from_runnable_config(config)
    user_id = configurable.user_id
    user_profile = get_user_profile(user_id, store)
    
    # Get the search parameters from state
    raw_search_params = state["search_params"]
    search_params = parse_search_params(raw_search_params)
    assert search_params is not None, "search_params should not be None in search_agent"     
    
    system_msg = news_search_prompt.PROMPT.format(search_params=search_params, user_profile=user_profile)

    # Use the LLM to generate a query
    response = model.invoke([SystemMessage(content=system_msg)])
    query = str(response.content).split("\n")[0]
    
    # Keep only ASCII characters
    normalized = unicodedata.normalize("NFD", query)
    query = "".join(c for c in normalized if unicodedata.category(c) != "Mn")

    print("Generated query:", query)
    print("Language code:", search_params.language)
    print("Max results:", search_params.max_results)

    # Call the search tool with the generated query 
    search_results = rapidapi_youtube.search_youtube(
            query=query,
            language=[search_params.language, "en"],
            max_results=search_params.max_results
    )

    # Filter the search results to only include one video per channel
    seen_channels = set()
    videos = []
    for video in search_results:
        if video.channel_title not in seen_channels:
            seen_channels.add(video.channel_title)
            videos.append(video)

    # This agent only updates the videos field in the state.
    return {"videos": videos}